### ISSUE TITLE
Installed but never loads

### ISSUE THREAD

**Issue by hollandb3** [yanivsegev/VSTS-DropPlan#16]
![2017-08-18_7-37-51](https://user-images.githubusercontent.com/31131141/29457527-87022bd2-83e8-11e7-821a-f59ae6a7131b.png)

Server is running TFS 2017.2

JS Error in console

Potentially unhandled rejection [1] TypeError: Object doesn't support property or method 'includes'
   at isDayOff (http://TFSSERVER:8080/tfs/_apis/public/gallery/publisher/yanivsegev/extension/Drop-plan-extension/1.0.46/assetbyname/scripts/DropPlanHelper.js:253:5)
   at Anonymous function (http://TFSSERVER:8080/tfs/_apis/public/gallery/publisher/yanivsegev/extension/Drop-plan-extension/1.0.46/assetbyname/scripts/DropPlanHelper.js:428:21)
   at getTable (http://TFSSERVER:8080/tfs/_apis/public/gallery/publisher/yanivsegev/extension/Drop-plan-extension/1.0.46/assetbyname/scripts/DropPlanHelper.js:426:17)
   at process (http://TFSSERVER:8080/tfs/_apis/public/gallery/publisher/yanivsegev/extension/Drop-plan-extension/1.0.46/assetbyname/scripts/DropPlanHelper.js:99:5)
   at processWorkItems (http://TFSSERVER:8080/tfs/_apis/public/gallery/publisher/yanivsegev/extension/Drop-plan-extension/1.0.46/assetbyname/scripts/DropPlanVSS.js:156:5)
   at processAllWorkItems (http://TFSSERVER

**Comment by yanivsegev** [comment]
I uploaded a fix, please try again.
